
run : run.o LinkedList.o
	g++ -g -Wall -Weffc++ -o run run.o LinkedList.o

run.o : run.cpp
	g++ -g -Wall -Weffc++ -c -o run.o run.cpp

LinkedList.o : LinkedList.cpp	
	g++ -g -Wall -Weffc++ -c -o LinkedList.o LinkedList.cpp